spring.config.import=file:/project/secrets/catalog/dev.properties
spring.datasource.main.url=${DB_URL}
spring.datasource.main.username=${DB_USERNAME}
spring.datasource.main.password=${DB_PASSWORD}
spring.datasource.movieinfo.url=${MOVIEINFO_DB_URL}
spring.datasource.movieinfo.username=${MOVIEINFO_DB_USERNAME}
spring.datasource.movieinfo.password=${MOVIEINFO_DB_PASSWORD}