spring.application.name=catalog
spring.cloud.config.enabled=false
spring.profiles.active=${SPRING_PROFILE}
server.port=8081
spring.cloud.circuitbreaker.resilience4j.enabled=${RESILIENCE4J_ENABLED}
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics
resilience4j.timelimiter.configs.instances.moviePlotService.timeoutDuration=${TIME_LIMITER_TIMEOUT_DURATION_MOVIEPLOTSERVICE}
resilience4j.timelimiter.configs.instances.moviePlotService.cancelRunningFuture=${TIME_LIMITER_CANCEL_RUNNNING_FUTURE_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.registerHealthIndicator=${CIRCUIT_BREAKER_REGISTER_HEALTH_INDICATOR_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.slidingWindowSize=${CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.slidingWindowType=${CIRCUIT_BREAKER_SLIDING_WINDOW_TYPE_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.failureRateThreshold=${CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.minimumNumberOfCalls=${CIRCUIT_BREAKER_MIN_NUMBER_OF_CALLS_MOVIEPLOTSERVICE}
resilience4j.circuitbreaker.configs.instances.moviePlotService.waitDurationInOpenState=${CIRCUIT_BREAKER_WAIT_DURATION_IN_OPEN_STATE_MOVIEPLOTSERVICE}
omdb.apikey=${OMDB_APIKEY}

