spring.application.name=application
spring.profiles.active=${SPRING_PROFILE}
management.endpoints.web.exposure.include=health,info,metrics
server.port=8080
url.catalog=${CATALOG_URL}
catalog.source=${CATALOG_SOURCE}
email.host=${EMAIL_HOST}
email.port=${EMAIL_PORT}
email.emailUsername=${EMAIL_USERNAME}
email.emailPassword=${EMAIL_PASSWORD}
logging.level.org.springframework.security=${LOGGING_LEVEL}
spring.config.import=classpath:catalog.properties
