spring.application.name=application
spring.profiles.active=${SPRING_PROFILE}
management.endpoints.web.exposure.include=health,info,metrics
server.port=8080
url.catalog=${CATALOG_URL}
catalog.source=${CATALOG_SOURCE}

#spring.config.import=classpath:catalog.properties
eureka.client.enabled=false


email.host=${EMAIL_HOST}
email.port=${EMAIL_PORT}
email.emailUsername=${EMAIL_USERNAME}
email.emailPassword=${EMAIL_PASSWORD}
logging.level.org.springframework.security=TRACE
token.auth.secret=${AUTH_SECRET}
token.auth.validityInMinutes=${AUTH_VALIDITY_MIN}
token.auth.issuer=${AUTH_ISSUER}
token.auth.audience=${AUTH_AUDIENCE}
