spring.config.import=file:/project/secrets/movieSecrets.properties
spring.datasource.main.url=${DB_URL}
spring.datasource.main.username=${DB_USERNAME}
spring.datasource.main.password=${DB_PASSWORD}
security.allowedOrigin=${ALLOWED_ORIGIN}
client.url=${CLIENT_URL}

